name: CICD and Unit Testing

on:
  push:
    branches:
      - master
      
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout-Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.x

      - name: Build
        run: go build

      - name: Test
        run: go test

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected to AWS EC2 instance"
            cd /home/ubuntu/CICD-UnitTesting
            git pull
            go build -o myapp .
            sudo systemctl restart cicd.service
            